### ISSUE TITLE
有些看不明白..

### ISSUE THREAD

**Issue by jwdzzhz777** [FrankFang/wheels#10]
学习下..
dom是document吗,
还有触发的事件是啥..

**Comment by Jiangyige** [comment]
dom是作者自己写的一个对象，封装了dom的一些操作，参见lib\dom\index.js

**Comment by FrankFang** [comment]
https://github.com/FrankFang/wheels/blob/master/lib/dom/index.js
dom 就是一个全局变量，内含一些常用的工具函数。
