### ISSUE TITLE
Pager中的分页器改变URL好像有点问题？

### ISSUE THREAD

**Issue by TaurusQ** [FrankFang/wheels#20]
点击下面的分页器之后的URL变成了“https://frankfang.github.io/wheels/demos/pager.html?&page=6”，应该是“https://frankfang.github.io/wheels/demos/pager.html?page=6”吧，“page=6”之前应该没有“&”

**Comment by FrankFang** [comment]
这个 & 是合法的，我为了代码简洁才没有去管它
