### ISSUE TITLE
关于空格和缩进问题

### ISSUE THREAD

**Issue by FrankFang** [FrankFang/wheels#3]
我会保证缩进的正确。
但是空格我不在意。
显然多一个空格或者少一个空格对代码的意义没有任何影响，而错误的缩进会误导人。

如果你这么在意冒号前的空格，就用自动格式化工具格式化一下吧。

这个项目没有 lint 检查，也不会有任何工程化的东西。我是用基本没有任何插件的 vim 来编辑这个项目的，如果你让我去在意空格，这会很影响我的思路。

而且空格对于代码阅读，也基本没有阻碍（除了处女座）。

我的观点（不一定对）：
1. 纠结空格，很无聊。
2. 打倒强迫症。

如果你们都觉得不舒服，那我发布之前跑一个自动加空格的脚本吧。

**Comment by kangaoxiaoshi** [comment]
这个是我私下提给方老师的问题，确实如方老师所说:  空格不会阻碍代码阅读、代码意义上也确实没有任何影响。
但下面是我个人观点（不一定对）
1、  既然写，且当别人提出来了时，为啥不按比较规范标准的来写 何为标准，可以看现在比较流行的开源框架
    1.1 https://github.com/vuejs/vue
    1.2  https://github.com/ecomfe/spec/blob/master/javascript-style-guide.md#user-content-2-%E4%BB%A3%E7%A0%81%E9%A3%8E%E6%A0%BC
2、 做培训编码方式、习惯、技巧，可能影响一批批的学子， 愿让他们从最开始就有一个比较好的开头，当养成习惯这真的是有益无害， 信不信我能用记事本给你写出跟vue规范一样的代码， 哈哈哈，（方老师其实我是心虚的， 逃！！）

哦， 对了，我不是处女座，也没有洁癖，只是当初入门时被别人指正过，然后坚持了下来

**Comment by FrankFang** [comment]
我认为「不要在意空格，把时间用来思考代码」就是个好头。

**Comment by FrankFang** [comment]
https://github.com/prettier/prettier#prettier

使用了这个插件，嗯，又是一个新工具……

https://github.com/FrankFang/wheels/commit/a1aae8850567470407c8bf26ec315d8a15a609b3
