### ISSUE TITLE
在dom index.js文件里面的every方法疑问

### ISSUE THREAD

**Issue by yilujun100** [FrankFang/wheels#4]
every里面的回调fn去call的时候最后一个参数i是不是多余了，因为我看上面的uniqueClass在调用every的时候回调函数里面就只有一个参数

**Comment by FrankFang** [comment]
你可以不使用这个 i，但是我调用的时候必须给你这个 i，否则你就不知道当前遍历到第几个元素了。

    dom.every(element.parentNode.children, (el, i) => {
      console.log(`这是第 ${i} 个元素`)
    })
